// packages/react/src/Badge.tsx
import type { ReactNode } from 'react';
import { cx } from './cx';

type BadgeProps = {
  variant?: 'success' | 'warning' | 'error' | 'info';
  dot?: boolean;
  /** Renders the badge as a spiky starburst seal (for "new"/"beta" flags). */
  starburst?: boolean;
  children?: ReactNode;
};

export function Badge({ variant, dot, starburst, children }: BadgeProps) {
  return (
    <span
      className={cx(
        'badge',
        variant && `badge--${variant}`,
        dot && 'badge--dot',
        starburst && 'badge--starburst',
      )}
    >
      {children}
    </span>
  );
}

// packages/angular/src/badge.ts
import { Component, input, computed, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'paul-badge',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'hostClasses()' },
  template: `<ng-content />`,
})
export class PaulBadgeComponent {
  readonly variant = input<'success' | 'warning' | 'error' | 'info'>();
  readonly dot = input(false);
  /** Renders the badge as a spiky starburst seal (for "new"/"beta" flags). */
  readonly starburst = input(false);

  readonly hostClasses = computed(() => {
    const classes = ['badge'];
    const v = this.variant();
    if (v) classes.push(`badge--${v}`);
    if (this.dot()) classes.push('badge--dot');
    if (this.starburst()) classes.push('badge--starburst');
    return classes.join(' ');
  });
}
