// packages/react/src/Divider.tsx
import { type HTMLAttributes } from 'react';
import { cx } from './cx';

type DividerProps = HTMLAttributes<HTMLHRElement> & {
  orientation?: 'horizontal' | 'vertical';
};

/**
 * A thin rule that separates content. Renders an <hr> (implicit
 * role="separator"); pass orientation="vertical" for use inside a flex row.
 */
export function Divider({ orientation = 'horizontal', className, ...props }: DividerProps) {
  return (
    <hr
      className={cx('divider', orientation === 'vertical' && 'divider--vertical', className)}
      aria-orientation={orientation}
      {...props}
    />
  );
}

// packages/angular/src/divider.ts
import { Component, input, computed, ChangeDetectionStrategy } from '@angular/core';

/**
 * A thin rule that separates content. Horizontal by default; pass
 * orientation="vertical" for use inside a flex row. Angular twin of the React
 * `Divider`; exposes role="separator".
 */
@Component({
  selector: 'paul-divider',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    role: 'separator',
    '[class]': 'hostClasses()',
    '[attr.aria-orientation]': 'orientation()',
  },
  template: ``,
})
export class PaulDividerComponent {
  readonly orientation = input<'horizontal' | 'vertical'>('horizontal');

  readonly hostClasses = computed(() =>
    this.orientation() === 'vertical' ? 'divider divider--vertical' : 'divider',
  );
}
