// packages/react/src/FunnelChart.tsx
import { type HTMLAttributes } from 'react';
import { cx } from './cx';
import { funnelStages } from './chartGeometry';

export type FunnelDatum = {
  label: string;
  value: number;
};

type FunnelChartProps = Omit<HTMLAttributes<HTMLDivElement>, 'children'> & {
  data: FunnelDatum[];
  /** Accessible name for the chart. Required. */
  label: string;
  /** Show the per-stage drop-off beside each row. Defaults to true. */
  showDropOff?: boolean;
  /** viewBox width in coordinate units. Defaults to 200. */
  width?: number;
  /** viewBox height in coordinate units. Defaults to 140. */
  height?: number;
};

/** Stage colour comes from the SEQUENTIAL ramp: funnel stages are ordered. */
const stageColor = (i: number, total: number) => {
  const step = total <= 1 ? 3 : Math.round(1 + (i / (total - 1)) * 3);
  return `var(--paul-chart-seq-${step + 1})`;
};

/**
 * Stage-to-stage conversion, drawn as narrowing bands. Pure SVG from
 * `chartGeometry`, matching the Angular `PaulFunnelChart`.
 *
 * The drop-off is what a funnel is read for, so it is rendered as text rather
 * than left to the taper — the widths carry the shape, the labels carry the
 * number.
 */
export function FunnelChart({
  data,
  label,
  showDropOff = true,
  width = 200,
  height = 140,
  className,
  ...props
}: FunnelChartProps) {
  const stages = funnelStages(
    data.map((d) => d.value),
    { width, height, padding: 2 },
  );
  const summary = data
    .map((d, i) => `${d.label} ${d.value} (${stages[i]?.percent ?? 0}%)`)
    .join(', ');
  const name = data.length > 0 ? `${label}: ${summary}` : label;

  return (
    <div className={cx('paul-chart', 'paul-chart--funnel', className)} {...props}>
      <div role="img" aria-label={name} className="paul-chart__figure">
        {data.length > 0 ? (
          <svg
            className="paul-chart__svg"
            viewBox={`0 0 ${width} ${height}`}
            preserveAspectRatio="none"
            aria-hidden="true"
            focusable="false"
          >
            {stages.map((stage) => (
              <path
                key={stage.index}
                className="paul-chart__stage"
                d={stage.path}
                fill={stageColor(stage.index, stages.length)}
              />
            ))}
          </svg>
        ) : (
          <span className="paul-chart__empty" aria-hidden="true">
            No data
          </span>
        )}
      </div>
      {data.length > 0 && (
        <ol className="paul-chart__legend">
          {data.map((d, i) => (
            <li key={d.label} className="paul-chart__legend-item">
              <span
                className="paul-chart__swatch"
                aria-hidden="true"
                style={{ backgroundColor: stageColor(i, data.length) }}
              />
              <span className="paul-chart__legend-label">{d.label}</span>
              <span className="paul-chart__legend-value">{d.value}</span>
              {showDropOff && i > 0 && (
                <span className="paul-chart__delta">−{stages[i]?.dropOff ?? 0}%</span>
              )}
            </li>
          ))}
        </ol>
      )}
    </div>
  );
}

// packages/angular/src/funnel-chart.ts
import { Component, input, computed, ChangeDetectionStrategy } from '@angular/core';
import { funnelStages } from './chart-geometry';

export interface PaulFunnelDatum {
  label: string;
  value: number;
}

/** Stage colour comes from the SEQUENTIAL ramp: funnel stages are ordered. */
function stageColor(i: number, total: number): string {
  const step = total <= 1 ? 3 : Math.round(1 + (i / (total - 1)) * 3);
  return `var(--paul-chart-seq-${step + 1})`;
}

/**
 * Stage-to-stage conversion, drawn as narrowing bands — the Angular twin of the
 * React `FunnelChart`.
 *
 * The drop-off is what a funnel is read for, so it is rendered as text rather
 * than left to the taper.
 */
@Component({
  selector: 'paul-funnel-chart',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': "'paul-chart paul-chart--funnel'" },
  template: `
    <div class="paul-chart__figure" role="img" [attr.aria-label]="name()">
      @if (data().length > 0) {
        <svg
          class="paul-chart__svg"
          [attr.viewBox]="viewBox()"
          preserveAspectRatio="none"
          aria-hidden="true"
          focusable="false"
        >
          @for (stage of stages(); track stage.index) {
            <path class="paul-chart__stage" [attr.d]="stage.path" [attr.fill]="stage.color"></path>
          }
        </svg>
      } @else {
        <span class="paul-chart__empty" aria-hidden="true">No data</span>
      }
    </div>
    @if (data().length > 0) {
      <ol class="paul-chart__legend">
        @for (d of data(); track d.label; let i = $index) {
          <li class="paul-chart__legend-item">
            <span class="paul-chart__swatch" aria-hidden="true" [style.background-color]="colorFor(i)"></span>
            <span class="paul-chart__legend-label">{{ d.label }}</span>
            <span class="paul-chart__legend-value">{{ d.value }}</span>
            @if (showDropOff() && i > 0) {
              <span class="paul-chart__delta">−{{ dropOffAt(i) }}%</span>
            }
          </li>
        }
      </ol>
    }
  `,
})
export class PaulFunnelChartComponent {
  readonly data = input<PaulFunnelDatum[]>([]);
  readonly label = input.required<string>();
  readonly showDropOff = input(true);
  readonly width = input(200);
  readonly height = input(140);

  readonly viewBox = computed(() => `0 0 ${this.width()} ${this.height()}`);

  private readonly layout = computed(() =>
    funnelStages(
      this.data().map((d) => d.value),
      { width: this.width(), height: this.height(), padding: 2 },
    ),
  );

  readonly stages = computed(() =>
    this.layout().map((stage) => ({
      ...stage,
      color: stageColor(stage.index, this.layout().length),
    })),
  );

  readonly name = computed(() => {
    const data = this.data();
    if (data.length === 0) return this.label();
    const layout = this.layout();
    const summary = data
      .map((d, i) => `${d.label} ${d.value} (${layout[i]?.percent ?? 0}%)`)
      .join(', ');
    return `${this.label()}: ${summary}`;
  });

  colorFor(i: number): string {
    return stageColor(i, this.data().length);
  }

  dropOffAt(i: number): number {
    return this.layout()[i]?.dropOff ?? 0;
  }
}
