// packages/react/src/Skeleton.tsx
import type { CSSProperties } from 'react';
import { cx } from './cx';

type SkeletonProps = {
  variant?: 'text' | 'circle' | 'rect';
  width?: string;
  height?: string;
};

export function Skeleton({ variant, width, height }: SkeletonProps) {
  const style: CSSProperties | undefined =
    width || height
      ? ({
          '--skeleton-w': width,
          '--skeleton-h': height,
        } as CSSProperties)
      : undefined;

  return (
    <div
      className={cx('skeleton', variant && `skeleton--${variant}`)}
      style={style}
    />
  );
}

// packages/angular/src/skeleton.ts
import { Component, input, computed, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'paul-skeleton',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClasses()',
    '[style.--skeleton-w]': 'width()',
    '[style.--skeleton-h]': 'height()',
  },
  template: ``,
})
export class PaulSkeletonComponent {
  readonly variant = input<'text' | 'circle' | 'rect'>('text');
  readonly width = input<string>();
  readonly height = input<string>();

  readonly hostClasses = computed(() => {
    return `skeleton skeleton--${this.variant()}`;
  });
}
