// packages/react/src/Switch.tsx
import { forwardRef, type ButtonHTMLAttributes } from 'react';
import { cx } from './cx';

type SwitchProps = Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'onChange'> & {
  /** Whether the switch is on. Controlled. */
  checked: boolean;
  /** Called with the next value when toggled. */
  onCheckedChange?: (checked: boolean) => void;
  disabled?: boolean;
};

/**
 * An on/off toggle. Controlled via `checked` + `onCheckedChange`. Exposes
 * role="switch" with aria-checked so assistive tech reads its state. Give it
 * an aria-label (or aria-labelledby) since it has no text of its own.
 */
export const Switch = forwardRef<HTMLButtonElement, SwitchProps>(
  function Switch({ checked, onCheckedChange, disabled, className, ...props }, ref) {
    return (
      <button
        ref={ref}
        type="button"
        role="switch"
        aria-checked={checked}
        disabled={disabled}
        onClick={() => onCheckedChange?.(!checked)}
        className={cx('switch', checked && 'switch--on', className)}
        {...props}
      >
        <span className="switch__thumb" />
      </button>
    );
  },
);

// packages/angular/src/switch.ts
import { Component, input, output, computed, ChangeDetectionStrategy } from '@angular/core';

/**
 * An on/off toggle. Controlled via `checked` + `checkedChange`. Exposes
 * role="switch" with aria-checked so assistive tech reads its state. Give it an
 * aria-label since it has no text of its own. Angular twin of the React `Switch`.
 */
@Component({
  selector: 'paul-switch',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button
      type="button"
      role="switch"
      [class]="btnClasses()"
      [attr.aria-checked]="checked()"
      [attr.aria-label]="ariaLabel() || null"
      [disabled]="disabled()"
      (click)="toggle()"
    >
      <span class="switch__thumb"></span>
    </button>
  `,
})
export class PaulSwitchComponent {
  readonly checked = input.required<boolean>();
  readonly disabled = input(false);
  readonly ariaLabel = input('', { alias: 'aria-label' });

  readonly checkedChange = output<boolean>();

  readonly btnClasses = computed(() => (this.checked() ? 'switch switch--on' : 'switch'));

  toggle(): void {
    if (!this.disabled()) this.checkedChange.emit(!this.checked());
  }
}
