// packages/react/src/TiltCard.tsx
import { useRef, type HTMLAttributes, type PointerEvent, type ReactNode } from 'react';
import { cx } from './cx';
import { usePrefersReducedMotion } from './usePrefersReducedMotion';

type TiltCardProps = HTMLAttributes<HTMLDivElement> & {
  /** Maximum rotation, in degrees, at the edges of the card. */
  maxTilt?: number;
  /** Show the cursor-tracking glare highlight. Defaults to true. */
  glare?: boolean;
  children: ReactNode;
};

/**
 * A surface that tilts in 3D toward the pointer, with an optional glare that
 * tracks the cursor. The effect is purely decorative — the content layer stays
 * readable — and it is pointer-driven only, so keyboard users are never left
 * without access. Under prefers-reduced-motion it renders as a flat card with
 * no tilt or glare. Content-agnostic: pass any children (a Card, an image…).
 */
export function TiltCard({
  maxTilt = 12,
  glare = true,
  className,
  children,
  ...rest
}: TiltCardProps) {
  const reduced = usePrefersReducedMotion();
  const innerRef = useRef<HTMLDivElement>(null);

  // No tilt, no glare, no pointer handlers — just a flat, static card.
  if (reduced) {
    return (
      <div className={cx('tilt-card', className)} {...rest}>
        <div className="tilt-card__inner">{children}</div>
      </div>
    );
  }

  const handleMove = (e: PointerEvent<HTMLDivElement>) => {
    const rect = e.currentTarget.getBoundingClientRect();
    if (rect.width === 0 || rect.height === 0) return;
    const px = (e.clientX - rect.left) / rect.width; // 0 (left) … 1 (right)
    const py = (e.clientY - rect.top) / rect.height; // 0 (top) … 1 (bottom)
    const rotateY = (px - 0.5) * 2 * maxTilt;
    const rotateX = -(py - 0.5) * 2 * maxTilt;
    const inner = innerRef.current;
    if (!inner) return;
    inner.style.setProperty('--paul-tilt-x', `${rotateX.toFixed(2)}deg`);
    inner.style.setProperty('--paul-tilt-y', `${rotateY.toFixed(2)}deg`);
    inner.style.setProperty('--paul-glare-x', `${(px * 100).toFixed(1)}%`);
    inner.style.setProperty('--paul-glare-y', `${(py * 100).toFixed(1)}%`);
    inner.dataset.active = 'true';
  };

  const handleLeave = () => {
    const inner = innerRef.current;
    if (!inner) return;
    inner.style.setProperty('--paul-tilt-x', '0deg');
    inner.style.setProperty('--paul-tilt-y', '0deg');
    delete inner.dataset.active;
  };

  return (
    <div
      className={cx('tilt-card', className)}
      onPointerMove={handleMove}
      onPointerLeave={handleLeave}
      {...rest}
    >
      <div ref={innerRef} className="tilt-card__inner">
        {glare && <div aria-hidden="true" className="tilt-card__glare" />}
        {children}
      </div>
    </div>
  );
}

// packages/angular/src/tilt-card.ts
import {
  Component,
  input,
  inject,
  viewChild,
  ElementRef,
  ChangeDetectionStrategy,
} from '@angular/core';
import { PaulReducedMotion } from './prefers-reduced-motion';

/**
 * A surface that tilts in 3D toward the pointer, with an optional glare that
 * tracks the cursor. Angular twin of the React `TiltCard`.
 *
 * The effect is decorative and pointer-driven only, so keyboard users are never
 * left without access to the content. Under prefers-reduced-motion it renders
 * as a flat card: no glare, no handlers bound, nothing to switch off.
 */
@Component({
  selector: 'paul-tilt-card',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    @if (reduced()) {
      <div class="tilt-card">
        <div #inner class="tilt-card__inner"><ng-content /></div>
      </div>
    } @else {
      <div class="tilt-card" (pointermove)="onMove($event)" (pointerleave)="onLeave()">
        <div #inner class="tilt-card__inner">
          @if (glare()) {
            <div aria-hidden="true" class="tilt-card__glare"></div>
          }
          <ng-content />
        </div>
      </div>
    }
  `,
})
export class PaulTiltCardComponent {
  /** Maximum rotation, in degrees, at the edges of the card. */
  readonly maxTilt = input(12);
  /** Show the cursor-tracking glare highlight. */
  readonly glare = input(true);

  readonly reduced = inject(PaulReducedMotion).reduced;

  private readonly inner = viewChild<ElementRef<HTMLElement>>('inner');

  onMove(event: PointerEvent): void {
    const root = event.currentTarget as HTMLElement;
    const rect = root.getBoundingClientRect();
    if (rect.width === 0 || rect.height === 0) return;

    const px = (event.clientX - rect.left) / rect.width; // 0 (left) … 1 (right)
    const py = (event.clientY - rect.top) / rect.height; // 0 (top) … 1 (bottom)
    const rotateY = (px - 0.5) * 2 * this.maxTilt();
    const rotateX = -(py - 0.5) * 2 * this.maxTilt();

    const inner = this.inner()?.nativeElement;
    if (!inner) return;
    inner.style.setProperty('--paul-tilt-x', `${rotateX.toFixed(2)}deg`);
    inner.style.setProperty('--paul-tilt-y', `${rotateY.toFixed(2)}deg`);
    inner.style.setProperty('--paul-glare-x', `${(px * 100).toFixed(1)}%`);
    inner.style.setProperty('--paul-glare-y', `${(py * 100).toFixed(1)}%`);
    inner.dataset['active'] = 'true';
  }

  onLeave(): void {
    const inner = this.inner()?.nativeElement;
    if (!inner) return;
    inner.style.setProperty('--paul-tilt-x', '0deg');
    inner.style.setProperty('--paul-tilt-y', '0deg');
    delete inner.dataset['active'];
  }
}
