// packages/angular/src/button.ts
import { Component, input, output, computed, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'paul-button',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClasses()',
    '[attr.disabled]': 'isDisabled() || null',
    '[attr.aria-disabled]': 'isDisabled() || null',
    '[attr.aria-busy]': 'loading() || null',
    '(click)': 'handleClick($event)',
  },
  template: `
    @if (href()) {
      <a [href]="href()" [class]="hostClasses()">
        <ng-content />
      </a>
    } @else {
      <ng-content />
    }
  `,
})
export class PaulButtonComponent {
  readonly variant = input<'primary' | 'secondary' | 'outline' | 'ghost' | 'danger'>();
  readonly size = input<'xs' | 'sm' | 'md' | 'lg'>();
  readonly disabled = input(false);
  readonly loading = input(false);
  readonly href = input<string>();

  readonly clicked = output<MouseEvent>();

  readonly isDisabled = computed(() => this.disabled() || this.loading());

  readonly hostClasses = computed(() => {
    const classes = ['btn'];
    const v = this.variant();
    const s = this.size();
    if (v) classes.push(`btn--${v}`);
    if (s && s !== 'md') classes.push(`btn--${s}`);
    return classes.join(' ');
  });

  handleClick(event: MouseEvent): void {
    if (!this.isDisabled()) {
      this.clicked.emit(event);
    }
  }
}

// packages/react/src/Button.tsx
import {
  forwardRef,
  type ButtonHTMLAttributes,
  type AnchorHTMLAttributes,
  type ReactNode,
} from 'react';
import { cx } from './cx';

type ButtonVariant = 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger';
type ButtonSize = 'xs' | 'sm' | 'md' | 'lg';

type BaseProps = {
  variant?: ButtonVariant;
  size?: ButtonSize;
  loading?: boolean;
  disabled?: boolean;
  children: ReactNode;
};

type ButtonAsButton = BaseProps &
  Omit<ButtonHTMLAttributes<HTMLButtonElement>, keyof BaseProps> & {
    href?: never;
  };

type ButtonAsAnchor = BaseProps &
  Omit<AnchorHTMLAttributes<HTMLAnchorElement>, keyof BaseProps> & {
    href: string;
  };

type ButtonProps = ButtonAsButton | ButtonAsAnchor;

export const Button = forwardRef<
  HTMLButtonElement | HTMLAnchorElement,
  ButtonProps
>(function Button(
  { variant, size, loading, disabled, className, children, ...props },
  ref,
) {
  const classes = cx(
    'btn',
    variant && `btn--${variant}`,
    size && size !== 'md' && `btn--${size}`,
    className,
  );

  if ('href' in props && props.href) {
    return (
      <a
        ref={ref as React.Ref<HTMLAnchorElement>}
        className={classes}
        aria-disabled={disabled || loading || undefined}
        {...props}
      >
        {children}
      </a>
    );
  }

  const { href: _, ...buttonProps } = props as ButtonAsButton;

  return (
    <button
      ref={ref as React.Ref<HTMLButtonElement>}
      className={classes}
      disabled={disabled || loading}
      aria-disabled={disabled || loading || undefined}
      aria-busy={loading || undefined}
      {...buttonProps}
      onClick={disabled || loading ? undefined : buttonProps.onClick}
    >
      {children}
    </button>
  );
});
