// packages/angular/src/card.ts
import { Component, input, computed, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'paul-card',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'hostClasses()' },
  template: `<ng-content />`,
})
export class PaulCardComponent {
  readonly variant = input<'elevated' | 'interactive'>();

  readonly hostClasses = computed(() => {
    const classes = ['card'];
    const v = this.variant();
    if (v) classes.push(`card--${v}`);
    return classes.join(' ');
  });
}

@Component({
  selector: 'paul-card-header',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'card__header' },
  template: `<ng-content />`,
})
export class PaulCardHeaderComponent {}

@Component({
  selector: 'paul-card-body',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'card__body' },
  template: `<ng-content />`,
})
export class PaulCardBodyComponent {}

@Component({
  selector: 'paul-card-footer',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'card__footer' },
  template: `<ng-content />`,
})
export class PaulCardFooterComponent {}

// packages/react/src/Card.tsx
import { forwardRef, type ReactNode, type HTMLAttributes } from 'react';
import { cx } from './cx';

type CardVariant = 'elevated' | 'interactive';

type CardProps = HTMLAttributes<HTMLDivElement> & {
  variant?: CardVariant;
  children: ReactNode;
};

const CardRoot = forwardRef<HTMLDivElement, CardProps>(
  function Card({ variant, className, children, ...props }, ref) {
    return (
      <div
        ref={ref}
        className={cx('card', variant && `card--${variant}`, className)}
        {...props}
      >
        {children}
      </div>
    );
  }
);

function Header({ className, children, ...props }: HTMLAttributes<HTMLDivElement>) {
  return <div className={cx('card__header', className)} {...props}>{children}</div>;
}

function Body({ className, children, ...props }: HTMLAttributes<HTMLDivElement>) {
  return <div className={cx('card__body', className)} {...props}>{children}</div>;
}

function Footer({ className, children, ...props }: HTMLAttributes<HTMLDivElement>) {
  return <div className={cx('card__footer', className)} {...props}>{children}</div>;
}

export const Card = Object.assign(CardRoot, { Header, Body, Footer });
