// packages/angular/src/modal.ts
import { Component, input, output, computed, effect, ChangeDetectionStrategy, ElementRef, viewChild } from '@angular/core';

@Component({
  selector: 'paul-modal',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '(document:keydown.escape)': 'handleEscape()',
  },
  template: `
    @if (open()) {
      <div class="modal__backdrop" (click)="handleBackdropClick()">
        <div class="modal__content" #content
          role="dialog"
          aria-modal="true"
          [attr.aria-labelledby]="titleId"
          (click)="$event.stopPropagation()">
          <ng-content />
        </div>
      </div>
    }
  `,
})
export class PaulModalComponent {
  readonly open = input(false);
  readonly closed = output<void>();

  private static nextId = 0;
  readonly titleId = `paul-modal-title-${PaulModalComponent.nextId++}`;

  handleBackdropClick(): void {
    this.closed.emit();
  }

  handleEscape(): void {
    if (this.open()) this.closed.emit();
  }
}

@Component({
  selector: 'paul-modal-header',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'modal__header' },
  template: `<ng-content />`,
})
export class PaulModalHeaderComponent {}

@Component({
  selector: 'paul-modal-body',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'modal__body' },
  template: `<ng-content />`,
})
export class PaulModalBodyComponent {}

@Component({
  selector: 'paul-modal-footer',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'modal__footer' },
  template: `<ng-content />`,
})
export class PaulModalFooterComponent {}

// packages/react/src/Modal.tsx
import { useEffect, useId, type ReactNode } from 'react';
import { createPortal } from 'react-dom';

type ModalProps = {
  open: boolean;
  onClose: () => void;
  title?: string;
  children: ReactNode;
};

function Header({ children }: { children: ReactNode }) {
  return <div className="modal__header">{children}</div>;
}

function Body({ children }: { children: ReactNode }) {
  return <div className="modal__body">{children}</div>;
}

function Footer({ children }: { children: ReactNode }) {
  return <div className="modal__footer">{children}</div>;
}

export function Modal({ open, onClose, title, children }: ModalProps) {
  const titleId = useId();

  useEffect(() => {
    if (!open) return;
    function handleKey(e: KeyboardEvent) {
      if (e.key === 'Escape') onClose();
    }
    document.addEventListener('keydown', handleKey);
    return () => document.removeEventListener('keydown', handleKey);
  }, [open, onClose]);

  if (!open) return null;

  return createPortal(
    <div className="modal__backdrop" onClick={onClose}>
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby={title ? titleId : undefined}
        className="modal"
        onClick={(e) => e.stopPropagation()}
      >
        {title && (
          <div id={titleId} className="modal__title">
            {title}
          </div>
        )}
        {children}
      </div>
    </div>,
    document.body,
  );
}

Modal.Header = Header;
Modal.Body = Body;
Modal.Footer = Footer;
