// packages/angular/src/ticker.ts
import {
  Component,
  input,
  inject,
  signal,
  computed,
  contentChild,
  viewChild,
  afterNextRender,
  DestroyRef,
  ElementRef,
  TemplateRef,
  ChangeDetectionStrategy,
} from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import { PaulReducedMotion } from './prefers-reduced-motion';

/** How long a touch keeps the strip frozen before the ambient scroll resumes. */
const TOUCH_RESUME_MS = 4000;

/**
 * A horizontal ticker strip with two modes: an accessible, auto-scrolling
 * container (`scroll`) and a decorative CSS marquee (`marquee`). Angular twin
 * of the React `Ticker`. Both loop seamlessly and both honour
 * prefers-reduced-motion.
 *
 * Content comes in as an `<ng-template>` rather than plain projection, because
 * the seamless loop renders the same content twice and projected content can
 * only be placed once:
 *
 * ```html
 * <paul-ticker label="News">
 *   <ng-template><span>Headline</span></ng-template>
 * </paul-ticker>
 * ```
 */
@Component({
  selector: 'paul-ticker',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet],
  host: { style: 'display: contents' },
  template: `
    @if (mode() === 'marquee') {
      <div [class]="rootClasses()" aria-hidden="true" [attr.data-direction]="direction()">
        <div class="ticker__track">
          <div class="ticker__group"><ng-container [ngTemplateOutlet]="body()" /></div>
          <div class="ticker__group"><ng-container [ngTemplateOutlet]="body()" /></div>
        </div>
      </div>
    } @else if (reduced()) {
      <!-- Reduced motion: a plain, single-copy scrollable row. No clone, no loop. -->
      <section [class]="rootClasses()" [attr.aria-label]="label()">
        <div class="ticker__group"><ng-container [ngTemplateOutlet]="body()" /></div>
      </section>
    } @else {
      <section
        #scroller
        [class]="rootClasses()"
        [attr.aria-label]="label()"
        [attr.data-direction]="direction()"
        (mouseenter)="paused.set(true)"
        (mouseleave)="paused.set(false)"
        (touchstart)="freezeForTouch()"
      >
        <div class="ticker__track" [attr.data-paused]="paused() || null">
          <div class="ticker__group"><ng-container [ngTemplateOutlet]="body()" /></div>
          <div #clone aria-hidden="true" inert class="ticker__group">
            <ng-container [ngTemplateOutlet]="body()" />
          </div>
        </div>
      </section>
    }
  `,
})
export class PaulTickerComponent {
  /** Accessible name for the strip. Scroll mode renders a labelled region. */
  readonly label = input.required<string>();
  /**
   * `scroll` (default) is a real scroll container with an ambient auto-scroll —
   * every item stays reachable. `marquee` is a decorative, aria-hidden CSS loop.
   */
  readonly mode = input<'scroll' | 'marquee'>('scroll');
  /** Which edge the strip sits on; picks the border side. */
  readonly edge = input<'top' | 'bottom'>('top');
  /** Which way the ambient motion travels. */
  readonly direction = input<'left' | 'right'>('left');
  /** Ambient auto-scroll speed for scroll mode, in px/sec. */
  readonly speed = input(40);

  readonly reduced = inject(PaulReducedMotion).reduced;
  readonly paused = signal(false);

  private readonly template = contentChild(TemplateRef);
  private readonly scroller = viewChild<ElementRef<HTMLElement>>('scroller');
  private readonly clone = viewChild<ElementRef<HTMLElement>>('clone');
  private readonly destroyRef = inject(DestroyRef);
  private resumeTimer: ReturnType<typeof setTimeout> | null = null;

  readonly body = computed(() => this.template() ?? null);

  readonly rootClasses = computed(() => {
    const classes = ['ticker'];
    if (this.mode() === 'marquee') classes.push('ticker--marquee');
    classes.push(this.edge() === 'top' ? 'ticker--top' : 'ticker--bottom');
    return classes.join(' ');
  });

  constructor() {
    afterNextRender(() => {
      this.dropCloneFromTabOrder();
      this.startAmbientScroll();
    });
    this.destroyRef.onDestroy(() => {
      if (this.resumeTimer) clearTimeout(this.resumeTimer);
    });
  }

  /**
   * Fallback for browsers without `inert`.
   *
   * The clone carries `inert` in the template, which drops its descendants
   * from the tab order and the accessibility tree together, before first
   * render. This used to be the only mechanism, and it left a gap: a lifecycle
   * hook runs after the DOM exists, so between render and this call the
   * duplicate held tabbable controls inside an aria-hidden container. The React
   * twin shipped that and axe flagged it on a live page -- hiding something
   * from assistive tech while leaving it reachable by keyboard is worse than
   * not hiding it, because the user lands on a control a screen reader insists
   * is not there.
   */
  private dropCloneFromTabOrder(): void {
    if ('inert' in HTMLElement.prototype) return;
    const focusables = this.clone()?.nativeElement.querySelectorAll<HTMLElement>(
      'a[href], button, input, select, textarea, [tabindex]',
    );
    focusables?.forEach((el) => {
      el.tabIndex = -1;
    });
  }

  /**
   * Advance scrollLeft each frame and wrap by one copy width for a seamless
   * loop. Pauses on hover/touch; user scrolling is left alone.
   */
  private startAmbientScroll(): void {
    const el = this.scroller()?.nativeElement;
    if (!el) return;

    const dir = this.direction() === 'left' ? 1 : -1;
    // Start the rightward strip one copy in, so it has somewhere to scroll back.
    if (dir < 0) el.scrollLeft = el.scrollWidth / 2;

    let frame = 0;
    let last = performance.now();
    const step = (now: number) => {
      const dt = now - last;
      last = now;
      const half = el.scrollWidth / 2;
      if (!this.paused() && half > 0) {
        let next = el.scrollLeft + (dir * this.speed() * dt) / 1000;
        if (next >= half) next -= half;
        else if (next < 0) next += half;
        el.scrollLeft = next;
      }
      frame = requestAnimationFrame(step);
    };
    frame = requestAnimationFrame(step);
    this.destroyRef.onDestroy(() => cancelAnimationFrame(frame));
  }

  freezeForTouch(): void {
    this.paused.set(true);
    if (this.resumeTimer) clearTimeout(this.resumeTimer);
    this.resumeTimer = setTimeout(() => this.paused.set(false), TOUCH_RESUME_MS);
  }
}

// packages/react/src/Ticker.tsx
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { cx } from './cx';
import { usePrefersReducedMotion } from './usePrefersReducedMotion';

type TickerProps = {
  /** Accessible name for the strip. Scroll mode renders a labelled region. */
  label: string;
  /**
   * `scroll` (default) is an accessible, real scroll container with an ambient
   * auto-scroll — every item stays reachable. `marquee` is a decorative,
   * aria-hidden CSS loop for pure flavour.
   */
  mode?: 'scroll' | 'marquee';
  /** Which edge the strip sits on; picks the border side. */
  edge?: 'top' | 'bottom';
  /** Which way the ambient motion travels. */
  direction?: 'left' | 'right';
  /** Ambient auto-scroll speed for scroll mode, in px/sec. */
  speed?: number;
  className?: string;
  children: ReactNode;
};

/** How long a touch keeps the strip frozen before the ambient scroll resumes. */
const TOUCH_RESUME_MS = 4000;

/**
 * A horizontal ticker strip with two modes: an accessible, auto-scrolling
 * container (`scroll`) and a decorative CSS marquee (`marquee`). Both loop
 * seamlessly and both honour prefers-reduced-motion. Content is passed as
 * children, so the strip stays content-agnostic.
 */
export function Ticker(props: TickerProps) {
  return props.mode === 'marquee' ? (
    <MarqueeTicker {...props} />
  ) : (
    <ScrollTicker {...props} />
  );
}

function edgeClassFor(edge: 'top' | 'bottom'): string {
  return edge === 'top' ? 'ticker--top' : 'ticker--bottom';
}

/** Decorative marquee: aria-hidden, CSS-driven, content duplicated for the loop. */
function MarqueeTicker({
  edge = 'top',
  direction = 'left',
  className,
  children,
}: TickerProps) {
  return (
    <div
      aria-hidden="true"
      data-direction={direction}
      className={cx('ticker', 'ticker--marquee', edgeClassFor(edge), className)}
    >
      <div className="ticker__track">
        <div className="ticker__group">{children}</div>
        <div className="ticker__group">{children}</div>
      </div>
    </div>
  );
}

/** Accessible scroll container with an ambient JS auto-scroll loop. */
function ScrollTicker({
  label,
  edge = 'top',
  direction = 'left',
  speed = 40,
  className,
  children,
}: TickerProps) {
  const reduced = usePrefersReducedMotion();
  const scrollerRef = useRef<HTMLElement>(null);
  const cloneRef = useRef<HTMLDivElement>(null);
  const [paused, setPaused] = useState(false);

  // Mirror `paused` into a ref so the animation-frame loop reads the latest
  // value without the scroll effect re-subscribing on every toggle.
  const pausedRef = useRef(false);
  useEffect(() => {
    pausedRef.current = paused;
  }, [paused]);

  // Fallback for browsers without `inert`.
  //
  // The clone carries `inert` in the markup, which drops its descendants from
  // the tab order and the accessibility tree together, before first paint. This
  // effect used to be the only mechanism, and it left a gap: an effect runs
  // after the DOM exists, so between render and this call the duplicate held
  // tabbable controls inside an aria-hidden container. Hiding something from
  // assistive tech while leaving it reachable by keyboard is worse than not
  // hiding it — the user lands on a control a screen reader insists is absent.
  useEffect(() => {
    if ('inert' in HTMLElement.prototype) return;
    const focusables = cloneRef.current?.querySelectorAll<HTMLElement>(
      'a[href], button, input, select, textarea, [tabindex]',
    );
    focusables?.forEach((el) => {
      el.tabIndex = -1;
    });
  });

  // Ambient scroll: advance scrollLeft each frame and wrap by one copy width
  // for a seamless loop. Pauses on hover/touch; user scrolling is left alone.
  useEffect(() => {
    if (reduced) return;
    const el = scrollerRef.current;
    if (!el) return;

    const dir = direction === 'left' ? 1 : -1;
    // Start the rightward strip one copy in, so it has somewhere to scroll back.
    if (dir < 0) el.scrollLeft = el.scrollWidth / 2;

    let raf = 0;
    let last = performance.now();
    const step = (now: number) => {
      const dt = now - last;
      last = now;
      const half = el.scrollWidth / 2;
      if (!pausedRef.current && half > 0) {
        let next = el.scrollLeft + (dir * speed * dt) / 1000;
        if (next >= half) next -= half;
        else if (next < 0) next += half;
        el.scrollLeft = next;
      }
      raf = requestAnimationFrame(step);
    };
    raf = requestAnimationFrame(step);
    return () => cancelAnimationFrame(raf);
  }, [reduced, direction, speed]);

  const resumeTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const freezeForTouch = () => {
    setPaused(true);
    if (resumeTimer.current) clearTimeout(resumeTimer.current);
    resumeTimer.current = setTimeout(() => setPaused(false), TOUCH_RESUME_MS);
  };

  const classes = cx('ticker', edgeClassFor(edge), className);

  // Reduced motion: a plain, single-copy scrollable row. No clone, no loop.
  if (reduced) {
    return (
      <section aria-label={label} className={classes}>
        <div className="ticker__group">{children}</div>
      </section>
    );
  }

  return (
    <section
      ref={scrollerRef}
      aria-label={label}
      data-direction={direction}
      className={classes}
      onMouseEnter={() => setPaused(true)}
      onMouseLeave={() => setPaused(false)}
      onTouchStart={freezeForTouch}
    >
      <div className="ticker__track" data-paused={paused || undefined}>
        <div className="ticker__group">{children}</div>
        <div ref={cloneRef} aria-hidden="true" inert className="ticker__group">
          {children}
        </div>
      </div>
    </section>
  );
}
